[package]
name = "solcery-game"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.7.8"
thiserror = "1.0.24"
borsh = "0.9.1"
borsh-derive = "0.9.0"
spl-token = {version="3.3.0", features = ["no-entrypoint"]}
solcery-data-types = { path = "../data-types" }

[dev-dependencies]
pretty_assertions = "0.6.1"
solana-program-test = "1.7.8"
solana-sdk = "1.7.8"

[lib]
name = "solcery_game"
crate-type = ["cdylib", "lib"]
