[package]
name = "solcery-vm"
version = "0.0.0"
license = "Apache-2.0"
homepage = "https://solcery.xyz/"
edition = "2021"

[dependencies]
borsh = "0.9.1"
#serde = { version = "1.0", features = ["derive"]  }
solana-program = "1.8.2"
thiserror = "1.0.24"
bytemuck = "1.7.2"
#tinyvec = {version = "1.3.1", features = ["rustc_1_40", "serde"]}
solcery-data-types = { path = "../data-types" }

[dev-dependencies]
pretty_assertions = "0.6.1"
solana-program-test = "1.8.2"
solana-sdk = "1.8.2"
test-case = "1.2.0"
