[package]
name = "fs_test"
version = "0.1.0-alpha"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = { version = "1", optional = true, features = ["derive"] }
borsh = "0.9.1"
solana-program = "1.7.8"
