[package]
name = "solcery-db-program"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.7.8"
borsh = "0.9.1"
spl-token = {version="3.3.0", features = ["no-entrypoint"]}
account-fs = { path = "../fs" }
solcery-db = { path = "../db" }

[dev-dependencies]
#pretty_assertions = "0.6.1"
#solana-program-test = "1.7.8"
#solana-sdk = "1.7.8"

[lib]
name = "solcery_db_program"
crate-type = ["cdylib", "lib"]
