[package]
name = "slice-rbtree"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.1"
bytemuck = {version = "1.7.2", features = ['derive','min_const_generics']}

[dev-dependencies]
#rand = {version = "0.8.5", features = ["min_const_gen"]}
criterion = "0.3"
paste = "1.0"
pretty_assertions = "1.3.0"

[[bench]]
name = "compare"
harness = false
