[package]
name = "slice-rbtree"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bitvec = "1.0.0"
borsh = "0.9.1"
bytemuck = {version = "1.7.2", features = ['derive','min_const_generics']}

[dev-dependencies]
paste = "1.0"
pretty_assertions = "1.3.0"
