name: CI

on:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - 'dev'
      - 'main'
    paths:
      - '**.rs'

  workflow_dispatch:

jobs:
  native:
    name: Native Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache toolchain
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            ~/.local/share/solana/
            target/
          key: ${{ runner.os }}-cargo-native

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true
          override: true

      - name: Build tests
        run: cargo test --no-run --verbose

      - name: Run tests
        run: cargo test --no-fail-fast --verbose
  onchain:
    name: On-chain Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache toolchain
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            ~/.local/share/solana/
            target/
          key: ${{ runner.os }}-cargo-onchain

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install Solana SDK
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.14.7/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          cargo-build-bpf --version
        
      - name: Build SBF
        run: cargo test-sbf --no-run --verbose
        
      - name: Test SBF
        run: cargo test-sbf --verbose
